version: "3.7"

services:   
    main_database_adm:
        image: postgres
        container_name: main_database
        networks:
            - main_network_db
        ports:
            - "5433:5432"
        volumes:
            - main_database:/var/lib/postgresql/data/:rw
            - ./main_database/:/var/tmp/
        environment:
          - POSTGRES_USER=${DB_USERNAME}
          - POSTGRES_PASSWORD=${DB_PASSWORD}
          - POSTGRES_DB=${DB_DATABASE}

volumes:
    main_database:

networks: 
    main_network_db:
        name: production_network
